[package]
name = "ckb-merkle-mountain-range"
version = "0.17.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
bytes = "0.4"
ckb-hash = { path = "../hash" }
ckb-merkle-mountain-range-core = { path = "core" }

[dev-dependencies]
faster-hex = "0.3"
criterion = "0.2"
rand = "0.6"
proptest = "0.9.4"
lazy_static = "1.3.0"

[[bench]]
name = "mmr_benchmark"
harness = false

[[bench]]
name = "helper_benchmark"
harness = false
