[package]
name = "ckb-verification"
version = "0.22.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
ckb-types = { path = "../util/types" }
ckb-store = { path = "../store" }
ckb-script = { path = "../script" }
ckb-pow = { path = "../pow" }
faketime = "0.2.0"
rayon = "1.0"
lru-cache = { git = "https://github.com/nervosnetwork/lru-cache", rev = "a35fdb8" }
ckb-traits = { path = "../traits" }
ckb-chain-spec = { path = "../spec" }
ckb-dao = { path = "../util/dao" }
ckb-logger = {path = "../util/logger"}
ckb-reward-calculator= { path = "../util/reward-calculator" }
failure = "0.1.5"
ckb-error = { path = "../error" }
enum-display-derive = "0.1.0"
tokio = "1.8"
futures = "0.1"
crossbeam-channel = "0.3"
ckb-future-executor = { path = "../util/future-executor" }

[dev-dependencies]
ckb-chain = { path = "../chain" }
ckb-shared = { path = "../shared" }
ckb-test-chain-utils = { path = "../util/test-chain-utils" }
rand = "0.6"
