[package]
name = "ckb-store"
version = "0.20.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
ckb-types = { path = "../util/types" }
ckb-db = { path = "../db" }
ckb-chain-spec = { path = "../spec" }
lru-cache = { git = "https://github.com/nervosnetwork/lru-cache", rev = "a35fdb8" }
ckb-script-data-loader = { path = "../script/data-loader" }
ckb-util = { path = "../util" }
ckb-logger = { path = "../util/logger" }
ckb-merkle-mountain-range = { path = "../util/merkle-mountain-range" }
lazy_static = "1.3.0"

[dev-dependencies]
tempfile = "3.0"
