[package]
name = "ckb-merkle-mountain-range-core"
version = "0.17.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
failure = "0.1.5"
bytes = "0.4"
