[package]
name = "ckb-stop-handler"
version = "0.22.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
parking_lot = "=0.7.1"
crossbeam-channel = "0.4"
ckb-logger = { path = "../logger" }
futures = "0.1"
